development:
  adapter: async

test:
  adapter: test

production:
  adapter: redis
  url: <%= ENV.fetch("STUDYCENTER_API_REDIS_HOST") { "redis://localhost:6379/1" } %>
  channel_prefix: studycenter_api_production
